### PR TITLE
use $TARGET name also for exe binary in MIYOO *.zip package + update .gitignore

### PR DESCRIPTION
**Pull request by Apaczer**

### CODE REVIEW

**Comment by irixxxx** [comment]
Have a look at my release-testing branch. It's not yet tested, but I believe it should resolve the issue. Comment here if there's still something off.

**Comment by irixxxx** [comment]
I checked dingux, opendingux, and miyoo builds, and they all work. @Apaczer if you have any objections or want me to change something else, reopen please.

**Comment by Apaczer** [comment]
Hi @irixxxx, tks for changes.

To DRY a little:
```diff
diff --git a/Makefile b/Makefile
index 68f65392..08461b27 100644
--- a/Makefile
+++ b/Makefile
@@ -116,7 +116,7 @@ PicoDrive.zip: $(TARGET)
 	mkdir .od_data
 	cp -r platform/linux/skin .od_data
 	cp platform/game_def.cfg .od_data
-	$(STRIP) $< -o .od_data/picodrive
+	$(STRIP) $< -o .od_data/$<
 	cd .od_data && zip -9 -r ../$@ *
 all: PicoDrive.zip
 endif
@@ -127,7 +127,7 @@ ifeq "$(PLATFORM)" "opendingux"
 	mkdir .od_data
 	cp -r platform/opendingux/data/. .od_data
 	cp platform/game_def.cfg .od_data
-	$(STRIP) $< -o .od_data/picodrive
+	$(STRIP) $< -o .od_data/$<
 .PHONY: .od_data
 
 ifneq (,$(filter %__DINGUX__, $(CFLAGS)))
```

In some future I would split Miyoo (ARM) from dingux/od (MIPS) for less confusion and add *.ipk with full dir structue for running binary, but I understand your time is scarce.

**Comment by irixxxx** [comment]
I did this deliberately, since the executable name is referenced by the desktop files or shell scripts.

Hand me a build rule for the ipk, and if changes are small enough and easily testable it might go into 2.00. The zip should go away, since there should be only one file per target.
BTW everything is done for the release, all tests are done (and all the bugs found by them are fixed). I'm basically set to pull it off in the next few days.

**Pull request closed without merging**
