### PR TITLE
revive pandora build and add some CI for it

### PR DESCRIPTION
**Pull request by notaz**
I want it to keep building

### CODE REVIEW

**Comment by irixxxx** [comment]
I'm really curious. Is this really working without further changes, after all the changes I did to the internal platform APIs? For reference, you might want to look at the psp platform directory. That has the most clean implementation of the current API version.

**Comment by notaz** [comment]
Yes it works. The only broken thing I noticed is that the screenshots no longer show up in save state menu, which can be dealt with later. The "secret" debug screens (L+R) are also gone, but I don't care about that.

**Comment by irixxxx** [comment]
Wow :-0. Scaling options work for SMS and GG too?
Sorry for asking this. I never got myself a Pandora, so I can't test.

As for CI, while being at it, I'm looking into setting something up for gp2x, psp, and miyoo. Going to merge this if I have at least one of those.

**Comment by notaz** [comment]
Added gp2x for you, with no helix but I'd consider it good enough.

And yeah SMS does no video output at all, will need to update some more stuff for pandora after all. As you mentioned a 2.0 release, I'm aiming for updating pandora's "official" release too.

**Comment by irixxxx** [comment]
Great, thanks for this. I'll have a look at psp (shouldn't be that difficult, toolchain is available on the net).
That should cover for the large part of the source code and prevent check-ins breaking something fundamentally. It indeed has happened from time to time :-/.
It might also be possible to do some minimal testing e.g. by using miniretro.

**Pull request merged**
