### PR TITLE
platform: Add miyoo support

### PR DESCRIPTION
**Pull request by jSTE0**
Builds with the toolchain from https://github.com/steward-fu/miyoo/.

### CODE REVIEW

**Comment by irixxxx** [comment]
Thanks. Will have a look.

I can't do official release builds for this though, since I do this only for devices I own and can test with myself.
If anybody wants to donate a device with that allwinner cpu I could support it with release builds...

**Comment by irixxxx** [comment]
@freq-mod since you supplied the miyoo build on the release page... is there something amiss here?

**Comment by freq-mod** [comment]
i think it's okay

**Comment by jSTE0** [comment]
> I can't do official release builds for this though, since I do this only for devices I own and can test with myself. If anybody wants to donate a device with that allwinner cpu I could support it with release builds...

I can make a release on my fork, there's already a pre-release there. The linked issue mentions a problem with the "Emulator controls" page though, none of the key bindings appear and reconfiguring them has no effect. I haven't investigated it yet, though it appears that it does work if you manually edit the configuration file.

**Comment by irixxxx** [comment]
There's no problem in doing a release build. That's mostly trivial.
I'm saying I can't give support to it since I don't have the hardware. I can't address issues specifically reported for such a build. I need at least a working emulation or simulation to do so, or the hardware.

However, I'm hosting external builds by others for those platforms but don't give much (or even any) support for platform related problems. That must come from those people supplying the build.

**Comment by jSTE0** [comment]
> I'm saying I can't give support to it since I don't have the hardware. I can't address issues specifically reported for such a build. I need at least a working emulation or simulation to do so, or the hardware.

Sure, I wasn't expecting support. It looks like issues tend to be filed against the CFW anyway (as can be seen from the linked issue), instead of the emulator itself, so support will come from the downstream community.

**Comment by freq-mod** [comment]
@irixxxx since I don't know about any other way of contacting you - if you are interested in obtaining miyoo device, I might donate one.

**Comment by irixxxx** [comment]
tsk... the email address is in the repo's boiler plate :-D

**Pull request merged**
