### PR TITLE
Mark-III extended FM sound unit. Correcting the treatment of color number 0

### PR DESCRIPTION
**Pull request by hiroshica**
Addition: Support for the Japanese Mark-III extended FM sound unit

### CODE REVIEW

**Comment by irixxxx** [comment]
Oops, just discovered this (WT..., no automatic email by github?). Is this still work in progress, or was there another reason for withdrawing the PR? Shall I review your changes nonetheless to iron out problems for later integration?

**Comment by hiroshica** [comment]
In Japan, if we do not receive a reply within 5 business days, we will consider it as unwillingness to end.

**Comment by irixxxx** [comment]
Sorry for that :-/. I have learned that I should review my dashboard on a
more regular basis. I honestly thought github would inform me by mail about
requests to my repo.

Just to clarify my time frame (I have to plan ahead since my spare time is
rather limited), I would like to complete my current task upto a certain
point to avoid leaving too many loose ends. I hope I can do this within the
rest of the week's spare time, which would leave me with some time to
review this during the next week. I truly hope this is OK with you.

**Comment by hiroshica** [comment]
I hit a weird button by mistake.

I'll pull-req. again if there are any problems.

**Comment by irixxxx** [comment]
Hmm, I think it still looks good. On first view I can't see anything strange.

While I was at it, I did some quick skimming of the code. Here are some first sight suggestions:
- Your build scripts contain local paths for your setup. That might not work someplace else. You should either remove or generalize them (I opted for documenting these things in the readme and leave the scripts out, but YMMV).
- There are some code fragments here and there, partly commented out, which I presume are leftovers from your development work. Are they still important for something?
- Is there a reason for using a float in pico/sound/sound.c line 443? floats are often slower on low profile CPUs (especially those without FPU), and I would say it works the same with a short.
- I would very much like to keep the commit messages and comments in one language if possible. That's the reason why I comment in English though it's not my native tongue. A lot of your commit messages are in "nihongo".
I'm not sure how to solve this; I could rebase the whole thing after merging in the PR and translate the messages, but I may miss something or make errors. I would very much appreciate some help here. I'm rather open to suggestions for this.

**Pull request closed without merging**
