### PR TITLE
Mark-III extended FM sound unit. Correcting the treatment of color number 0 and Corrections to the point The Japanese comment deletion as you pointed out might destroy commits, so we only delete a few.

### PR DESCRIPTION
**Pull request by hiroshica**
Mark-III extended FM sound unit. Correcting the treatment of color number 0 and Corrections to the point
The Japanese comment deletion as you pointed out might destroy commits, so we only delete a few.

### CODE REVIEW

**Comment by irixxxx** [comment]
FYI I'm now about to merge your changes. Please bear with me. I've not much experience with the upstream end of handling a PR.

I'm currently looking for the right way to do the merge. I think I'll break it down into three parts:
- YM2413 support
- SMS/Mark III color 0 fixes
- new platforms

... and the PR now starts to looking strange since a lot of my own commits are now also in it. What happened?

**Comment by hiroshica** [comment]
No problem.
Thank you for your time.

**Comment by irixxxx** [comment]
I now have a consolidated branch with your changes, redacted and cleaned up a bit for better alignment with my current branch.
- I don't understand f6d629e however. I would like to understand this, since there may be a bug in the logic. Do you have an example where it doesn't work correctly without this fix?
- I would like to understand the color 0 stuff. Can you point me to something where this was wrong before and is now OK?

**Comment by hiroshica** [comment]
When the priority flag of BG is on, it seems to be the correct behavior that the color number 0 is applied.

**Comment by irixxxx** [comment]
Thanks for the example. Before I do double work here: have you tried to verify this against the available documents?
This one appears to be the most complete: https://segaretro.org/Sega_Master_System_VDP_documentation_(2002-11-12).

SMS and Mode 4 isn't really well maintained in Picodrive. Now that I tried some stuff I discovered that 8 bit rendering modes didn't work at all... fixed that for linux, but I have the impression there might be more to this.

**Comment by irixxxx** [comment]
BTW, the changes to SDL handling appear to do nothing more but use pkg-config instead of sdl-config. Is there an advantage in this?

**Comment by irixxxx** [comment]
So... done, after rebasing on master and squashing a lot of commits together.
Since I've done this for the 1st time, please review and feel free to comment.

**Pull request closed without merging**
